OnlineVagtplan/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static


admin.site.site_header = 'OnlineVagtPlan Administration'
admin.site.site_title = 'Keeper Of The Voulentears'
admin.site.index_title = 'Admin Page'


urlpatterns = [
    path("admin/", admin.site.urls),
]

urlpatterns += [
    path("", include("shiftbooker.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shiftbooker/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("movies/", views.MovieListView.as_view(), name="movies"),
    path("movie/<int:pk>", views.MovieDetailView.as_view(), name="movie-detail"),
    path("volunteers/", views.VolunteerListView.as_view(), name="volunteers"),
    path(
        "volunteers/<int:pk>",
        views.VolunteerDetailView.as_view(),
        name="volunteer-detail",
    ),
    path("shift/<int:pk>", views.ShiftDetailView.as_view(), name="shift-detail"),
    path(
        "shift/signup/<int:shift_id>",
        views.sign_up_for_shift,
        name="sign_up_for_shift",
    ),
    path(
        "shift/remove/<int:shift_id>/",
        views.remove_user_from_shift,
        name="remove_user_from_shift",
    ),
    path("accounts/", include("django.contrib.auth.urls")),
    path("create_user/", views.create_user, name="create-user"),
    path("create_show/", views.create_show, name="create-show"),
    path("create_shift/", views.create_shift, name="create-shift"),
]

shiftbooker/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.contrib.auth.models import AbstractUser, UserManager


class CustomUserManager(UserManager):
    def get_by_natural_key(self, username):
        return self.get(username__iexact=username)


class User(AbstractUser):
    """Class representing a user"""

    registered = models.DateField(
        ("Registration Date"), auto_now=False, auto_now_add=True
    )
    phone = models.CharField(max_length=100)
    shifts_taken = models.IntegerField("Number of shifts taken", default=0)
    objects = CustomUserManager()

    class Meta(AbstractUser.Meta):
        swappable = "AUTH_USER_MODEL"
        permissions = (("can_view_users_shifts", "Can view users and shifts"),)

    def get_absolute_url(self):
        """Returns the URL to access a particular instance of movie."""
        return reverse("volunteer-detail", args=[str(self.id)])


class Movie(models.Model):
    """Class representing a movie"""

    title = models.CharField(max_length=200)
    date = models.DateTimeField()
    duration = models.IntegerField()
    poster = models.ImageField(
        upload_to="", height_field=None, width_field=None, max_length=None, blank=True
    )

    # Metadata
    class Meta:
        ordering = ["date"]

    # Methods
    def get_absolute_url(self):
        """Returns the URL to access a particular instance of movie."""
        return reverse("movie-detail", args=[str(self.id)])

    def __str__(self):
        """String for representing the MyModelName object (in Admin site etc.)."""
        return self.title


class Shift(models.Model):
    """Class representing a shift"""

    SHIFT_TYPES = (
        ("m", "Maintenance"),
        ("s", "Shop"),
        ("c", "Cleaning"),
        ("o", "A/V Operations"),
        ("p", "Event Planning"),
    )

    shift_type = models.CharField(
        max_length=1,
        choices=SHIFT_TYPES,
    )
    date = models.DateTimeField()
    duration = models.IntegerField()
    movie = models.ForeignKey("Movie", on_delete=models.CASCADE)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True
    )

    # Metadata
    class Meta:
        pass

    # Methods
    def get_absolute_url(self):
        """Returns the URL to access a particular instance of MyModelName."""
        return reverse("shift-detail", args=[str(self.id)])

    def __str__(self):
        """String for representing the MyModelName object (in Admin site etc.)."""
        return f"{self.movie.title}, {self.date}"

shiftbooker/forms.py
from django.forms import (
    ModelForm,
    ValidationError,
    DateTimeInput,
    PasswordInput,
)
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from shiftbooker.models import Movie, Shift
from django.contrib.auth import get_user_model


class CreateUserForm(ModelForm):
    def clean(self):
        data = super().clean()
        if not (data["phone"]).isdigit() or len(data["phone"]) != 8:
            raise ValidationError(
                ("Invalid Input - Phone Number Must Consist of 8 Digits")
            )
        return data

    class Meta:
        model = get_user_model()

        fields = [
            "username",
            "password",
            "first_name",
            "last_name",
            "email",
            "phone",
            "groups",
            "shifts_taken",
        ]
        widgets = {
            "password": PasswordInput(),
        }


class CreateShowForm(ModelForm):
    def clean(self):
        data = super().clean()  # ???

        # Check if a date is not in the past.
        if data["date"] < timezone.now():
            raise ValidationError(("Invalid Input - date must not be in the past"))

        # Check if duration is positive
        if data["duration"] < 0:
            raise ValidationError(("Invalid Input - duration must non-negative"))

        return data

    class Meta:
        model = Movie
        fields = "__all__"
        labels = {
            "title": _("Title of Movie"),
            "date": _("Date and Time of Showstart"),
            "duration": _("Duration of Show"),
            "poster": _("Image for Movie-Poster (optional)"),
        }
        widgets = {
            "date": DateTimeInput(
                format=("%Y-%m-%dT%H:%M"), attrs={"type": "datetime-local"}
            )
        }


class CreateShiftForm(ModelForm):
    def clean(self):
        data = super().clean()

        # Check if a date is not in the past.
        if data["date"] < timezone.now():
            raise ValidationError(("Invalid Input - date must not be in the past"))

        # Check if duration is positive
        if data["duration"] < 0:
            raise ValidationError(("Invalid Input - duration must non-negative"))

        return data

    class Meta:
        model = Shift
        fields = "__all__"
        widgets = {
            "date": DateTimeInput(
                format=("%Y-%m-%dT%H:%M"), attrs={"type": "datetime-local"}
            )
        }

shiftbooker/views.py
from django.shortcuts import get_object_or_404, redirect
from .models import Shift, Movie
from .forms import CreateUserForm, CreateShowForm, CreateShiftForm
from django.shortcuts import render
from django.views import generic
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group


# Create your views here.
@login_required
def index(request):
    """Index site of the booking system"""
    context = {
        "news": "This is a placeholder for a news object.",
        "movies": sorted(Movie.objects.all(), key=lambda x: x.title),
        "users": get_user_model().objects.all(),
    }
    return render(request, "index.html", context)


@login_required
def sign_up_for_shift(request, shift_id):
    # Retrieve the shift object from the database
    shift = get_object_or_404(Shift, pk=shift_id)

    if request.method == "POST":
        # Handle the POST request to sign up for the shift
        selected_user_id = request.POST.get("selected_user")
        if selected_user_id:
            # Assign the selected user to the shift (assuming 'user' is a ForeignKey in 'Shift' model)
            user = get_user_model().objects.get(id=selected_user_id)
            shift.user = user
            shift.save()
            return redirect(
                "movie-detail", pk=shift.movie.id
            )  # Replace with your actual URL pattern name for shift details

    # Handle the GET request to display the form
    user_list = (
        get_user_model().objects.all()
    )  # You can modify this to get the list of available users
    return render(
        request,
        "shiftbooker/shift_detail.html",
        {"shift": shift, "user_list": user_list},
    )


@login_required
@permission_required("shiftbooker.can_view_users_shifts")
def remove_user_from_shift(request, shift_id):
    shift = get_object_or_404(Shift, pk=shift_id)
    shift.user = None  # Assuming 'user' is a ForeignKey in 'Shift' model
    shift.save()

    # Redirect to a success page or back to the same page
    return redirect(shift.movie.get_absolute_url())


@login_required
@permission_required("shiftbooker.can_view_users_shifts")
def create_user(request):
    if request.method == "POST":
        form = CreateUserForm(request.POST)

        if form.is_valid():
            data = form.cleaned_data
            get_user_model().objects.create_user(
                username=data["username"],
                password=data["password"],
                first_name=data["first_name"],
                last_name=data["last_name"],
                email=data["email"],
                phone=data["phone"],
                shifts_taken=data["shifts_taken"],
            )
            new_user = get_user_model().objects.get(username=data["username"])
            group = Group.objects.get(name=data["groups"][0])
            group.user_set.add(new_user)

            return redirect("volunteers")

    else:
        form = CreateUserForm()

    context = {
        "form": form,
    }

    return render(request, "shiftbooker/create_user.html", context)


@login_required
@permission_required("shiftbooker.can_view_users_shifts")
def create_show(request):
    if request.method == "POST":
        form = CreateShowForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()
            return redirect("movies")

    else:
        form = CreateShowForm()

    context = {
        "form": form,
    }

    return render(request, "shiftbooker/create_show.html", context)


@login_required
@permission_required("shiftbooker.can_view_users_shifts")
def create_shift(request):
    if request.method == "POST":
        form = CreateShiftForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect("movies")

    else:
        form = CreateShiftForm()

    context = {
        "form": form,
    }

    return render(request, "shiftbooker/create_shift.html", context)


class MovieListView(LoginRequiredMixin, generic.ListView):
    model = Movie


class MovieDetailView(LoginRequiredMixin, generic.DetailView):
    model = Movie

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["avail_shifts"] = self.get_object().shift_set.filter(user=None)
        return context


class VolunteerListView(PermissionRequiredMixin, LoginRequiredMixin, generic.ListView):
    permission_required = "shiftbooker.can_view_users_shifts"
    model = get_user_model()

    template_name = "shiftbooker/volunteer_list.html"

    def get_queryset(self):
        queryset = get_user_model().objects.filter(groups__name="volunteer")
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["shifts"] = Shift.objects.all()
        return context


class VolunteerDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = "shiftbooker/volunteer_detail.html"
    model = get_user_model()
    context_object_name = "volunteer"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["shift_list"] = Shift.objects.all()
        return context


class ShiftDetailView(LoginRequiredMixin, generic.DetailView):
    model = Shift

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["user_list"] = get_user_model().objects.all()
        return context

templates/shiftbooker/create_shift.html
{% extends "base.html" %}

{% block content %}
  <h1>Create Shift</h1>
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

templates/shiftbooker/create_show.html
{% extends "base.html" %}

{% block content %}
  <h1>Create Show</h1>
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

templates/shiftbooker/create_user.html
{% extends "base.html" %}

{% block content %}
  <h1>Create User</h1>
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

templates/shiftbooker/movie_detail.html
{% extends "base.html" %}

{% block content %}
<div class="text-center">
<h1>Title: {{ movie.title }}</h1>
{% if movie.poster %}
  {% load static %}
  <img class="card-img-top w-25 mx-auto" style="padding:10px;"  src="{% static 'img/' %}{{ movie.poster }}">
{% endif %}
<p><strong>Date:</strong> {{ movie.date }}</p>
<p><strong>Duration:</strong> {{ movie.duration }} minutes </p>
{% comment %} <p><strong>Poster:</strong> {{ movie.poster }}</p> {% endcomment %}
<!--    Slow algorithm. please fix :Clown_emoji:🤡 -->
</div>
<div style="margin-left:20px;margin-top:20px;padding-right: 20px;">
  <h4>Available shifts: </h4>
  <div class="list-group">
  {% if avail_shifts %}
    <ul class="list-group">
      <div class="container text-center">
        <div class="row">
          <div class="col">
            <li class="list-group-item border-0">Shift Type</li>
          </div>
          <div class="col">
            <li class="list-group-item border-0">Date and Time</li>
          </div>
          <div class="col">
            <li class="list-group-item border-0">Shift Duration in Minutes</li>
          </div>
        </div>
      </div>
    </ul>
    {% endif%}
    {% for shift in avail_shifts %}
    {% if not shift.user %}
    <a href="{{ shift.get_absolute_url }}" class="list-group-item list-group-item-action list-group-item-success">
      <div class="container text-center">
        <div class="row">
          <div class="col">
            {{ shift.get_shift_type_display}}
          </div>
          <div class="col"> 
            {{ shift.date}}
          </div>
          <div class="col">
            {{ shift.duration}}
          </div>
        </div>
      </div>
    </a>
    {% endif %}
    {% empty %}
    <p>There are no shifts to show</p>
    {% endfor %}
  </div>
  {% if perms.shiftbooker.can_view_users_shifts %}
  <br>
  <h4>Full shifts: </h4>
  {% if avail_shifts|length != movie.shift_set.all|length %}
  <div class="list-group">
    <ul class="list-group">
      <div class="container text-center">
        <div class="row">
          <div class="col">
            <li class="list-group-item border-0">Shift Type</li>
          </div>
          <div class="col">
            <li class="list-group-item border-0">Date and Time</li>
          </div>
          <div class="col">
            <li class="list-group-item border-0">Shift Duration in Minutes</li>
          </div>
          <div class="col">
            <li class="list-group-item border-0">User Assigned to shift</li>
          </div>
        </div>
      </div>
    </ul>
    {% else %}
      <p>There are no shifts to show</p>
    {% endif %}
    
    {% for shift in movie.shift_set.all %}
    {% if shift.user %}
    <a href="{{ shift.get_absolute_url }}" class="list-group-item list-group-item-action list-group-item-danger">
      <div class="container text-center">
        <div class="row">
          <div class="col">
            {{ shift.get_shift_type_display}}
          </div>
          <div class="col">
            {{ shift.date}}
          </div>
          <div class="col">
            {{ shift.duration}}
          </div>
          <div class="col">
            {{shift.user}}
          </div>
        </div>
      </div>
    </a>
    {% endif %}
    {% endfor %}
    {% endif %}
  </div>
</div>
{% endblock %}

templates/shiftbooker/movie_list.html
{% extends "base.html" %}
{% block content %}
<div class="row" style="padding-top:20px;">
  {% for movie in movie_list %}
  <div class="col-3 mb-4">
    <div class="card" style="height:100%">
      {% load static %}
      {%if movie.poster %}
      <img class="card-img-top" src="{% static 'img/' %}{{ movie.poster }}" alt="This shit aint workin'">
      {% endif %}
      <div class="card-body d-flex flex-column">
        <div class="flex-grow-1">
        </div>
        <h5 class="card-title">{{ movie.title }}</h5>
        <p class="card-text"><strong>Date:</strong> {{ movie.date }}</p>
        <p class="card-text"><strong>Duration:</strong> {{ movie.duration }} minutes</p>
        <br>
        <a href="{{ movie.get_absolute_url }}" class="btn btn-primary mt-auto">Details</a>
      </div>
    </div>
  </div>
  {% empty %}
  <p>There are no movies</p>
  {% endfor %}
</div>
</div>
{% endblock %}

templates/shiftbooker/shift_detail.html
{% extends "base.html" %}
{% block content %}
<div class="card text-center">
    <div class="card-header">
        {{ shift.movie.title }}
    </div>
    <div class="card-body">
        {% load static %}
        {%if shift.movie.poster %}
        <img class="card-img-top w-25" style="padding:10px;" src="{% static 'img/' %}{{ shift.movie.poster }}">
        {% endif %}
        <h5 class="card-title">Volunteer shift type: {{ shift.get_shift_type_display }}</h5>
        <p class="card-text">{{ shift.date }}, duration: {{ shift.duration }} minutes</p>
        {% if not shift.user %}
        {% if perms.shiftbooker.can_view_users_shifts %}
            <form action="{% url 'sign_up_for_shift' shift.id %}" method="post">
                {% csrf_token %}
                <div class="form-group text-center">
                    <label for="user_select">Select a user:</label>
                    <select class="form-control w-25 mx-auto m-3" id="user_select" name="selected_user">
                        {% for user in user_list %}
                            <option value="{{ user.id }}">{{ user.username }}</option>
                        {% endfor %}
                    </select>
                </div>
                <input type="submit" value="Assign User" class="btn btn-success">
            </form>

        {% else %}
        <form action="{% url 'sign_up_for_shift' shift.id%}" method="post">
            {% csrf_token %}
            <input type="hidden" name="selected_user" value="{{ user.id }}">
            <input type="hidden" name="shift_id" value="{{ shift.id }}">
            <input type="submit" value="Sign up for shift!" class="btn btn-success">
        </form>
        {% endif %}
        {% elif perms.shiftbooker.can_view_users_shifts %}
        <form action="{% url 'remove_user_from_shift' shift.id %}" method="post">
           {% csrf_token %}
           <input type="submit" value="Remove user from shift!" class="btn btn-success">
        </form>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/shiftbooker/volunteer_detail.html
{% extends "base.html" %}
{% block content %}
{% if volunteer.name %}
<h1> {{ volunteer.name }}</h1>
{% else %}
<h1> {{ volunteer.username }}</h1>
{% endif %}

<div class="row" style="padding-top:20px;">
    {% for shift in shift_list %}
    {% if volunteer == shift.user %}
    <div class="col-3 mb-4">
      <div class="card" style="height:100%">
        <div class="card-body d-flex flex-column">
          <div class="flex-grow-1"></div> 
          <h2>Type: {{ shift.get_shift_type_display }}</h2>
          <p class="card-text" style="margin-bottom:0px"><strong>Date:</strong> {{ shift.date }}</p>
          <p class="card-text" style="margin-bottom:0px"><strong>Duration:</strong> {{ shift.duration }}</p>
          <p class="card-text" style="margin-bottom:0px"><strong>Movie:</strong> {{ shift.movie }}</p>
          <br>
          <a href="{{ shift.get_absolute_url }}" class="btn btn-primary mt-auto">Show Shift</a>
        </div>
      </div>
    </div>
    {% endif %}
    {% endfor %}
  </div>
  </div>
{% endblock %}

templates/shiftbooker/volunteer_list.html
{% extends "base.html" %}
{% block content %}
<div class="row" style="padding-top:20px;">
  {% for volunteer in user_list %}
  <div class="col-3 mb-4">
    <div class="card" style="height:100%">
      <div class="card-body d-flex flex-column">
        <div class="flex-grow-1 align-self-start">
          <h5 class="card-title">
            <strong>Name</strong>: 
            {% if volunteer.first_name and volunteer.last_name %}
            {{ volunteer.first_name }} {{ volunteer.last_name }}
            {% else %}
              {{ volunteer.username }}
            {% endif %}
          </h5>
          <p class="card-text" style="margin-bottom:0px"><strong>Phone:</strong> {{ volunteer.phone }}</p>
          {% if volunteer.email %}
            <p class="card-text"><strong>E-mail:</strong> {{ volunteer.email }}</p>
          {% endif %}
        </div>
        <br> <!-- very important don't -->
          <a href="{{ volunteer.get_absolute_url }}" class="btn btn-primary mt-auto">Shifts</a>
        </div>
    </div>
  </div>
  {% empty %}
  <p>There are no volunteers</p>
  {% endfor %}
</div>
</div>
{% endblock %}